[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my_project"
version = "0.1.0"
dependencies = [
    "pytest",
]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]