name: Python CI

on:
  push:                     # Ejecutar en cada push a cualquier rama
    branches:
      - main
      - Dev                # Limitado a dev y main
  pull_request:             # Ejecutar también en cada pull request
    branches:
      - main
      - Dev

jobs:
  test:                     # Definimos un trabajo llamado "test"
    runs-on: ubuntu-latest  # Usaremos un contenedor Linux (Ubuntu)

    steps:                  # Pasos para ejecutar la aplicacion
    - name: Check out code
      uses: actions/checkout@v3   # Descargar el código del repositorio

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11      # Configuramos Python 3.9 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip   
        pip install -r requirements.txt
    
    - name: Configure PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV
    - name: Run tests
      run: pytest               # Ejecutamos las pruebas con pytest
